### ISSUE TITLE
Filmstrip raises to scroll to new highlighted Range

### ISSUE THREAD

**Issue by azaroth42** [IIIF/m2#394] opened 2015-01-27 20:41 UTC
Steps to reproduce:

1.  Load vatican manifest by URL from http://dlss-dev-azaroth.stanford.edu/prezi/vatican/manifest.json  (images won't load as the reference is localhost)
2. Click forwards 7 times to folio 2 recto

Expected Behavior: filmstrip does not change
Actual Behavior: filmstrip raises above the ... icon preventing it from being lowered

![screen shot 2015-01-27 at 12 41 22 pm](https://cloud.githubusercontent.com/assets/871868/5926689/d783dcb0-a621-11e4-8457-0b575a9e4ce5.png)

**Comment by rsinghal** [comment] 2015-01-28 19:19
duplicate of #378

**Closed by rsinghal** 2015-01-28 19:19 UTC
