### ISSUE TITLE
filmstrip ... button appears under raised filmstrip

### ISSUE THREAD

**Issue by azaroth42** [IIIF/m2#392] opened 2015-01-27 20:24 UTC
Steps to reproduce:

1.  Go into 3x3 mode
2.  Select [America] 
3. ... button appears underneath the filmstrip

![screen shot 2015-01-27 at 12 23 54 pm](https://cloud.githubusercontent.com/assets/871868/5926361/64195b1c-a61f-11e4-8c33-031bc16c20f9.png)

**Comment by rsinghal** [comment] 2015-01-28 19:20
duplicate of #378

**Closed by rsinghal** 2015-01-28 19:20 UTC
